"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { usePathname } from "next/navigation";
import { GoogleAnalytics } from "@next/third-parties/google";
import Popover from "@/components/PopOver/PopOver";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const isAdminPage = pathname.startsWith("/admin");

  return (
    <html lang="pt">
      <GoogleAnalytics gaId="G-55TG5DG4FH" />

      <body className={inter.className}>
        <UserProvider>
          {!isAdminPage && (
            <Navbar
              home="/"
              cpu="/computadores"
              smartphones="/celulares"
              games="/jogos"
            />
          )}
          {children}
          <Popover />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
